# Generated by Django 5.2.17 on 2026-10-05 14:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContatoDaPessoa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('canal', models.TextField(choices=[('EMAIL', 'E-mail')], default='EMAIL')),
                ('valor', models.CharField(max_length=254)),
                ('origem', models.TextField(choices=[('FONTE_ACADEMICA', 'Fonte acadêmica'), ('EGRESSO', 'Informado pelo egresso')])),
                ('fonte', models.TextField(null=True)),
                ('posicao', models.PositiveSmallIntegerField(null=True)),
                ('obtido_em', models.DateTimeField()),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='academico.pessoa')),
            ],
            options={
                'indexes': [models.Index(fields=['pessoa', 'origem', 'obtido_em'], name='contato_politica_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('canal', 'EMAIL')), name='contato_canal_email'), models.CheckConstraint(condition=models.Q(('origem__in', ['FONTE_ACADEMICA', 'EGRESSO'])), name='contato_origem_conhecida'), models.CheckConstraint(condition=models.Q(models.Q(('fonte__isnull', False), ('origem', 'FONTE_ACADEMICA'), ('posicao__isnull', False)), models.Q(('fonte__isnull', True), ('origem', 'EGRESSO'), ('posicao__isnull', True)), _connector='OR'), name='contato_proveniencia_coerente'), models.CheckConstraint(condition=models.Q(('valor', ''), _negated=True), name='contato_valor_nao_vazio'), models.CheckConstraint(condition=models.Q(('fonte', ''), _negated=True), name='contato_fonte_nao_vazia'), models.UniqueConstraint(condition=models.Q(('origem', 'FONTE_ACADEMICA')), fields=('pessoa', 'fonte', 'obtido_em', 'posicao'), name='contato_observacao_unica')],
            },
        ),
    ]
