# Generated by Django 5.2.17 on 2026-10-01 17:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
        ('campanha', '0001_initial'),
        ('instrumento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('iniciada_em', models.DateTimeField()),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='campanha.campanha')),
                ('conclusao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='academico.conclusaoacademica')),
            ],
            options={
                'ordering': ['iniciada_em', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('texto', models.TextField(null=True)),
                ('escala', models.IntegerField(null=True)),
                ('complemento', models.TextField(null=True)),
                ('opcao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='instrumento.opcao')),
                ('participacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respostas', to='participacao.participacao')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='instrumento.pergunta')),
            ],
        ),
        migrations.CreateModel(
            name='RespostaOpcao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('opcao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='instrumento.opcao')),
                ('resposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='participacao.resposta')),
            ],
        ),
        migrations.AddField(
            model_name='resposta',
            name='opcoes',
            field=models.ManyToManyField(related_name='+', through='participacao.RespostaOpcao', to='instrumento.opcao'),
        ),
        migrations.AddConstraint(
            model_name='participacao',
            constraint=models.UniqueConstraint(fields=('campanha', 'conclusao'), name='participacao_par_unico'),
        ),
        migrations.AddConstraint(
            model_name='respostaopcao',
            constraint=models.UniqueConstraint(fields=('resposta', 'opcao'), name='resposta_opcao_unica'),
        ),
        migrations.AddConstraint(
            model_name='resposta',
            constraint=models.UniqueConstraint(fields=('participacao', 'pergunta'), name='resposta_pergunta_unica'),
        ),
        migrations.AddConstraint(
            model_name='resposta',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('opcao__isnull', False), ('texto__isnull', False)), models.Q(('escala__isnull', False), ('opcao__isnull', False)), models.Q(('escala__isnull', False), ('texto__isnull', False)), _connector='OR', _negated=True), name='resposta_um_valor_direto'),
        ),
        migrations.AddConstraint(
            model_name='resposta',
            constraint=models.CheckConstraint(condition=models.Q(('texto', ''), _negated=True), name='resposta_texto_nao_vazio'),
        ),
        migrations.AddConstraint(
            model_name='resposta',
            constraint=models.CheckConstraint(condition=models.Q(('complemento', ''), _negated=True), name='resposta_complemento_nao_vazio'),
        ),
    ]
