# Generated by Django 5.2.17 on 2026-10-01 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participacao',
            name='concluida_em',
            field=models.DateTimeField(null=True),
        ),
    ]
