# Generated by Django 5.2.17 on 2026-10-04 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
        ('campanha', '0001_initial'),
        ('declaracao', '0001_initial'),
        ('participacao', '0002_participacao_concluida_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='participacao',
            name='formacao_declarada',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='participacao', to='declaracao.formacaodeclarada'),
        ),
        migrations.AlterField(
            model_name='participacao',
            name='conclusao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='academico.conclusaoacademica'),
        ),
        migrations.AddConstraint(
            model_name='participacao',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('conclusao__isnull', False), ('formacao_declarada__isnull', True)), models.Q(('conclusao__isnull', True), ('formacao_declarada__isnull', False)), _connector='OR'), name='participacao_ancora_unica'),
        ),
    ]
