# Generated by Django 5.2.17 on 2026-10-05 14:43

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
        ('campanha', '0001_initial'),
        ('contato', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteDeMobilizacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=120)),
                ('unidades', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None)),
                ('nivel', models.TextField(null=True)),
                ('ano_minimo', models.PositiveSmallIntegerField(null=True)),
                ('ano_maximo', models.PositiveSmallIntegerField(null=True)),
                ('curso', models.TextField(null=True)),
                ('escopo_institucional', models.BooleanField()),
                ('escopo_unidades', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ('excluidas_por_mobilizacao', models.PositiveIntegerField(default=0)),
                ('confirmado_em', models.DateTimeField()),
                ('operador', models.TextField()),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='campanha.campanha')),
            ],
            options={
                'ordering': ['-confirmado_em', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='MembroDoLote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('situacao', models.TextField(choices=[('SEM_CONTATO', 'Sem contato'), ('NAO_TENTADO', 'Não tentado'), ('EM_TENTATIVA', 'Em tentativa'), ('SUBMETIDO_AO_TRANSPORTE', 'Submetido ao transporte'), ('FALHA_DE_TRANSPORTE', 'Falha de transporte')])),
                ('tentativa_iniciada_em', models.DateTimeField(null=True)),
                ('resultado_em', models.DateTimeField(null=True)),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='campanha.campanha')),
                ('contato', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contato.contatodapessoa')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='membros', to='mobilizacao.lotedemobilizacao')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='academico.pessoa')),
            ],
        ),
        migrations.AddConstraint(
            model_name='lotedemobilizacao',
            constraint=models.CheckConstraint(condition=models.Q(('nome', ''), _negated=True), name='lote_nome_nao_vazio'),
        ),
        migrations.AddConstraint(
            model_name='lotedemobilizacao',
            constraint=models.CheckConstraint(condition=models.Q(('operador', ''), _negated=True), name='lote_operador_nao_vazio'),
        ),
        migrations.AddConstraint(
            model_name='lotedemobilizacao',
            constraint=models.CheckConstraint(condition=models.Q(('unidades__isnull', True), models.Q(('unidades', []), _negated=True), _connector='OR'), name='lote_unidades_nulo_ou_nao_vazio'),
        ),
        migrations.AddConstraint(
            model_name='lotedemobilizacao',
            constraint=models.CheckConstraint(condition=models.Q(('nivel', ''), _negated=True), name='lote_nivel_nao_vazio'),
        ),
        migrations.AddConstraint(
            model_name='lotedemobilizacao',
            constraint=models.CheckConstraint(condition=models.Q(('curso', ''), _negated=True), name='lote_curso_nao_vazio'),
        ),
        migrations.AddConstraint(
            model_name='lotedemobilizacao',
            constraint=models.CheckConstraint(condition=models.Q(('ano_minimo__isnull', True), ('ano_maximo__isnull', True), ('ano_minimo__lte', models.F('ano_maximo')), _connector='OR'), name='lote_anos_coerentes'),
        ),
        migrations.AddConstraint(
            model_name='lotedemobilizacao',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('escopo_institucional', True), ('escopo_unidades', [])), models.Q(('escopo_institucional', False), ('unidades__isnull', False), models.Q(('escopo_unidades', []), _negated=True)), _connector='OR'), name='lote_escopo_coerente'),
        ),
        migrations.AddConstraint(
            model_name='membrodolote',
            constraint=models.UniqueConstraint(fields=('lote', 'pessoa'), name='membro_unico_no_lote'),
        ),
        migrations.AddConstraint(
            model_name='membrodolote',
            constraint=models.UniqueConstraint(condition=models.Q(('situacao', 'SEM_CONTATO'), _negated=True), fields=('campanha', 'pessoa'), name='membro_uma_abordagem_por_campanha'),
        ),
        migrations.AddConstraint(
            model_name='membrodolote',
            constraint=models.CheckConstraint(condition=models.Q(('situacao__in', ['SEM_CONTATO', 'NAO_TENTADO', 'EM_TENTATIVA', 'SUBMETIDO_AO_TRANSPORTE', 'FALHA_DE_TRANSPORTE'])), name='membro_situacao_conhecida'),
        ),
        migrations.AddConstraint(
            model_name='membrodolote',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('contato__isnull', True), ('situacao', 'SEM_CONTATO')), models.Q(models.Q(('situacao', 'SEM_CONTATO'), _negated=True), ('contato__isnull', False)), _connector='OR'), name='membro_sem_contato_coerente'),
        ),
        migrations.AddConstraint(
            model_name='membrodolote',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('resultado_em__isnull', True), ('situacao__in', ['SEM_CONTATO', 'NAO_TENTADO']), ('tentativa_iniciada_em__isnull', True)), models.Q(('resultado_em__isnull', True), ('situacao', 'EM_TENTATIVA'), ('tentativa_iniciada_em__isnull', False)), models.Q(('resultado_em__gte', models.F('tentativa_iniciada_em')), ('resultado_em__isnull', False), ('situacao__in', ['SUBMETIDO_AO_TRANSPORTE', 'FALHA_DE_TRANSPORTE']), ('tentativa_iniciada_em__isnull', False)), _connector='OR'), name='membro_instantes_coerentes'),
        ),
    ]
