# Generated by Django 5.2.17 on 2026-10-01 00:58

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fonte', models.TextField()),
                ('id_externo', models.TextField()),
                ('nome', models.TextField(null=True)),
                ('incorporado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('fonte', 'id_externo'), name='pessoa_origem_unica'), models.CheckConstraint(condition=models.Q(('fonte', ''), _negated=True), name='pessoa_fonte_nao_vazio'), models.CheckConstraint(condition=models.Q(('id_externo', ''), _negated=True), name='pessoa_id_externo_nao_vazio'), models.CheckConstraint(condition=models.Q(('nome', ''), _negated=True), name='pessoa_nome_nao_vazio')],
            },
        ),
        migrations.CreateModel(
            name='ConclusaoAcademica',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fonte', models.TextField()),
                ('id_externo', models.TextField()),
                ('curso', models.TextField(null=True)),
                ('unidade', models.TextField(null=True)),
                ('nivel', models.TextField(null=True)),
                ('modalidade', models.TextField(null=True)),
                ('forma_oferta', models.TextField(null=True)),
                ('ano_conclusao', models.PositiveSmallIntegerField(null=True)),
                ('data_conclusao', models.DateField(null=True)),
                ('incorporado_em', models.DateTimeField(auto_now_add=True)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conclusoes', to='academico.pessoa')),
            ],
            options={
                'ordering': ['ano_conclusao', 'id'],
                'constraints': [models.UniqueConstraint(fields=('fonte', 'id_externo'), name='conclusao_origem_unica'), models.CheckConstraint(condition=models.Q(('fonte', ''), _negated=True), name='conclusao_fonte_nao_vazio'), models.CheckConstraint(condition=models.Q(('id_externo', ''), _negated=True), name='conclusao_id_externo_nao_vazio'), models.CheckConstraint(condition=models.Q(('curso', ''), _negated=True), name='conclusao_curso_nao_vazio'), models.CheckConstraint(condition=models.Q(('unidade', ''), _negated=True), name='conclusao_unidade_nao_vazio'), models.CheckConstraint(condition=models.Q(('nivel', ''), _negated=True), name='conclusao_nivel_nao_vazio'), models.CheckConstraint(condition=models.Q(('modalidade', ''), _negated=True), name='conclusao_modalidade_nao_vazio'), models.CheckConstraint(condition=models.Q(('forma_oferta', ''), _negated=True), name='conclusao_forma_oferta_nao_vazio'), models.CheckConstraint(condition=models.Q(('data_conclusao__isnull', True), models.Q(('ano_conclusao__isnull', False), ('ano_conclusao', django.db.models.functions.datetime.ExtractYear('data_conclusao'))), _connector='OR'), name='conclusao_ano_coerente_com_data')],
            },
        ),
    ]
