# Generated by Django 5.2.17 on 2026-10-01 11:40

import django.db.models.constraints
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pesquisa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.TextField()),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('nome', ''), _negated=True), name='pesquisa_nome_nao_vazio')],
            },
        ),
        migrations.CreateModel(
            name='Secao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('posicao', models.PositiveIntegerField()),
                ('titulo', models.TextField(null=True)),
                ('texto', models.TextField(null=True)),
                ('encaminhamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='encaminhadas', to='instrumento.secao')),
            ],
            options={
                'ordering': ['posicao'],
            },
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('posicao', models.PositiveIntegerField()),
                ('tipo', models.TextField(choices=[('ESCOLHA_UNICA', 'Escolha Unica'), ('ESCOLHA_MULTIPLA', 'Escolha Multipla'), ('TEXTO_CURTO', 'Texto Curto'), ('ESCALA', 'Escala')])),
                ('texto', models.TextField()),
                ('texto_explicativo', models.TextField(null=True)),
                ('obrigatoria', models.BooleanField()),
                ('escala_inicio', models.IntegerField(null=True)),
                ('escala_fim', models.IntegerField(null=True)),
                ('escala_rotulo_inicio', models.TextField(null=True)),
                ('escala_rotulo_fim', models.TextField(null=True)),
                ('secao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='perguntas', to='instrumento.secao')),
            ],
            options={
                'ordering': ['posicao'],
            },
        ),
        migrations.CreateModel(
            name='Opcao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('posicao', models.PositiveIntegerField()),
                ('texto', models.TextField()),
                ('complemento_textual', models.BooleanField(default=False)),
                ('regra_finaliza', models.BooleanField(default=False)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcoes', to='instrumento.pergunta')),
                ('regra_destino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='regras_que_apontam', to='instrumento.secao')),
            ],
            options={
                'ordering': ['posicao'],
            },
        ),
        migrations.CreateModel(
            name='Versao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('designacao', models.TextField()),
                ('estado', models.TextField(choices=[('RASCUNHO', 'Rascunho'), ('PUBLICADA', 'Publicada')], default='RASCUNHO')),
                ('publicada_em', models.DateTimeField(null=True)),
                ('titulo', models.TextField(null=True)),
                ('texto_abertura', models.TextField(null=True)),
                ('texto_encerramento', models.TextField(null=True)),
                ('origem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='derivadas', to='instrumento.versao')),
                ('pesquisa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versoes', to='instrumento.pesquisa')),
            ],
            options={
                'ordering': ['designacao'],
            },
        ),
        migrations.AddField(
            model_name='secao',
            name='versao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='secoes', to='instrumento.versao'),
        ),
        migrations.AddConstraint(
            model_name='pergunta',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('secao', 'posicao'), name='pergunta_posicao_unica'),
        ),
        migrations.AddConstraint(
            model_name='pergunta',
            constraint=models.CheckConstraint(condition=models.Q(('posicao__gt', 0)), name='pergunta_posicao_positiva'),
        ),
        migrations.AddConstraint(
            model_name='pergunta',
            constraint=models.CheckConstraint(condition=models.Q(('tipo__in', ['ESCOLHA_UNICA', 'ESCOLHA_MULTIPLA', 'TEXTO_CURTO', 'ESCALA'])), name='pergunta_tipo_valido'),
        ),
        migrations.AddConstraint(
            model_name='pergunta',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('escala_fim__isnull', False), ('escala_inicio__isnull', False), ('escala_inicio__lt', models.F('escala_fim')), ('tipo', 'ESCALA')), models.Q(models.Q(('tipo', 'ESCALA'), _negated=True), ('escala_fim__isnull', True), ('escala_inicio__isnull', True), ('escala_rotulo_fim__isnull', True), ('escala_rotulo_inicio__isnull', True)), _connector='OR'), name='pergunta_escala_coerente'),
        ),
        migrations.AddConstraint(
            model_name='pergunta',
            constraint=models.CheckConstraint(condition=models.Q(('texto', ''), _negated=True), name='pergunta_texto_nao_vazio'),
        ),
        migrations.AddConstraint(
            model_name='pergunta',
            constraint=models.CheckConstraint(condition=models.Q(('texto_explicativo', ''), _negated=True), name='pergunta_texto_explicativo_nao_vazio'),
        ),
        migrations.AddConstraint(
            model_name='pergunta',
            constraint=models.CheckConstraint(condition=models.Q(('escala_rotulo_inicio', ''), _negated=True), name='pergunta_escala_rotulo_inicio_nao_vazio'),
        ),
        migrations.AddConstraint(
            model_name='pergunta',
            constraint=models.CheckConstraint(condition=models.Q(('escala_rotulo_fim', ''), _negated=True), name='pergunta_escala_rotulo_fim_nao_vazio'),
        ),
        migrations.AddConstraint(
            model_name='opcao',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('pergunta', 'posicao'), name='opcao_posicao_unica'),
        ),
        migrations.AddConstraint(
            model_name='opcao',
            constraint=models.CheckConstraint(condition=models.Q(('posicao__gt', 0)), name='opcao_posicao_positiva'),
        ),
        migrations.AddConstraint(
            model_name='opcao',
            constraint=models.UniqueConstraint(fields=('pergunta', 'texto'), name='opcao_texto_unico'),
        ),
        migrations.AddConstraint(
            model_name='opcao',
            constraint=models.UniqueConstraint(condition=models.Q(('complemento_textual', True)), fields=('pergunta',), name='opcao_complemento_unico'),
        ),
        migrations.AddConstraint(
            model_name='opcao',
            constraint=models.CheckConstraint(condition=models.Q(('regra_destino__isnull', False), ('regra_finaliza', True), _negated=True), name='opcao_uma_regra'),
        ),
        migrations.AddConstraint(
            model_name='opcao',
            constraint=models.CheckConstraint(condition=models.Q(('texto', ''), _negated=True), name='opcao_texto_nao_vazio'),
        ),
        migrations.AddConstraint(
            model_name='versao',
            constraint=models.UniqueConstraint(fields=('pesquisa', 'designacao'), name='versao_designacao_unica'),
        ),
        migrations.AddConstraint(
            model_name='versao',
            constraint=models.CheckConstraint(condition=models.Q(('estado__in', ['RASCUNHO', 'PUBLICADA'])), name='versao_estado_valido'),
        ),
        migrations.AddConstraint(
            model_name='versao',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('estado', 'PUBLICADA'), ('publicada_em__isnull', False)), models.Q(('estado', 'RASCUNHO'), ('publicada_em__isnull', True)), _connector='OR'), name='versao_publicada_em_coerente'),
        ),
        migrations.AddConstraint(
            model_name='versao',
            constraint=models.CheckConstraint(condition=models.Q(('origem', models.F('id')), _negated=True), name='versao_origem_outra'),
        ),
        migrations.AddConstraint(
            model_name='versao',
            constraint=models.CheckConstraint(condition=models.Q(('designacao', ''), _negated=True), name='versao_designacao_nao_vazio'),
        ),
        migrations.AddConstraint(
            model_name='versao',
            constraint=models.CheckConstraint(condition=models.Q(('titulo', ''), _negated=True), name='versao_titulo_nao_vazio'),
        ),
        migrations.AddConstraint(
            model_name='versao',
            constraint=models.CheckConstraint(condition=models.Q(('texto_abertura', ''), _negated=True), name='versao_texto_abertura_nao_vazio'),
        ),
        migrations.AddConstraint(
            model_name='versao',
            constraint=models.CheckConstraint(condition=models.Q(('texto_encerramento', ''), _negated=True), name='versao_texto_encerramento_nao_vazio'),
        ),
        migrations.AddConstraint(
            model_name='secao',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('versao', 'posicao'), name='secao_posicao_unica'),
        ),
        migrations.AddConstraint(
            model_name='secao',
            constraint=models.CheckConstraint(condition=models.Q(('posicao__gt', 0)), name='secao_posicao_positiva'),
        ),
        migrations.AddConstraint(
            model_name='secao',
            constraint=models.CheckConstraint(condition=models.Q(('titulo', ''), _negated=True), name='secao_titulo_nao_vazio'),
        ),
        migrations.AddConstraint(
            model_name='secao',
            constraint=models.CheckConstraint(condition=models.Q(('texto', ''), _negated=True), name='secao_texto_nao_vazio'),
        ),
    ]
