# Generated by Django 5.2.17 on 2026-10-02 19:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
        ('campanha', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnapshotAnalitico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('capturado_em', models.DateTimeField()),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='campanha.campanha')),
            ],
            options={
                'ordering': ['capturado_em', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RegistroDoSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('elegivel_no_snapshot', models.BooleanField()),
                ('curso', models.TextField(null=True)),
                ('unidade', models.TextField(null=True)),
                ('nivel', models.TextField(null=True)),
                ('modalidade', models.TextField(null=True)),
                ('forma_oferta', models.TextField(null=True)),
                ('ano_conclusao', models.PositiveSmallIntegerField(null=True)),
                ('data_conclusao', models.DateField(null=True)),
                ('conclusao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='academico.conclusaoacademica')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='analitico.snapshotanalitico')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('snapshot', 'conclusao'), name='registro_conclusao_unica_no_snapshot')],
            },
        ),
    ]
