# Generated by Django 5.2.17 on 2026-10-04 21:10

import django.db.models.deletion
from django.db import migrations, models

_LOTE = 1000


def verificar_pares(participacoes):
    pares = {}
    for p in participacoes:
        par = (p.campanha_id, p.conclusao_id)
        if par in pares:
            raise RuntimeError("Preenchimento histórico ambíguo; nenhuma linha alterada.")
        pares[par] = p.pk
    return pares


def preencher(apps, schema_editor):
    Participacao = apps.get_model("participacao", "Participacao")
    Registro = apps.get_model("analitico", "RegistroDoSnapshot")
    alias = schema_editor.connection.alias
    pares = verificar_pares(Participacao.objects.using(alias).filter(conclusao__isnull=False))
    lote = []
    registros = Registro.objects.using(alias).select_related("snapshot").only(
        "id", "conclusao_id", "snapshot__campanha_id"
    )
    for registro in registros.iterator(chunk_size=_LOTE):
        pk = pares.get((registro.snapshot.campanha_id, registro.conclusao_id))
        if pk is None:
            continue  # sem Participação: os dois campos ficam NULL, como já estão
        registro.participacao_id = pk
        registro.origem_formacao = "institucional"
        lote.append(registro)
        if len(lote) == _LOTE:
            Registro.objects.using(alias).bulk_update(lote, ["participacao", "origem_formacao"])
            lote = []
    if lote:
        Registro.objects.using(alias).bulk_update(lote, ["participacao", "origem_formacao"])


def reverter(apps, schema_editor):
    apps.get_model("analitico", "RegistroDoSnapshot").objects.using(
        schema_editor.connection.alias).update(participacao=None, origem_formacao=None)


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
        ('analitico', '0001_initial'),
        ('participacao', '0003_participacao_formacao_declarada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrodosnapshot',
            name='origem_formacao',
            field=models.CharField(choices=[('institucional', 'Institucional'), ('declarada_validada_fonte_digital', 'Fonte Digital'), ('declarada_validada_acervo', 'Acervo')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='registrodosnapshot',
            name='participacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='participacao.participacao'),
        ),
        migrations.RunPython(preencher, reverter),
        migrations.AddConstraint(
            model_name='registrodosnapshot',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('origem_formacao__isnull', True), ('participacao__isnull', True)), models.Q(('origem_formacao__in', ['institucional', 'declarada_validada_fonte_digital', 'declarada_validada_acervo']), ('participacao__isnull', False)), _connector='OR'), name='registro_origem_com_participacao'),
        ),
    ]
