# Generated by Django 5.2.17 on 2026-10-08 23:50

import django.contrib.postgres.fields
import django.db.models.functions.text
import django.db.models.lookups
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oportunidade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.TextField()),
                ('resumo', models.TextField()),
                ('categoria', models.TextField(choices=[('cursos', 'Cursos e formação continuada'), ('eventos', 'Eventos'), ('pesquisa_extensao', 'Pesquisa e extensão'), ('carreira', 'Carreira e empregabilidade'), ('empreendedorismo', 'Empreendedorismo'), ('outras', 'Outras iniciativas')])),
                ('unidade_responsavel', models.TextField(blank=True, default='')),
                ('endereco', models.TextField()),
                ('inicio', models.DateField()),
                ('fim', models.DateField()),
                ('publico_unidades', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None)),
                ('publico_niveis', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None)),
                ('publico_cursos', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None)),
                ('publicada_em', models.DateTimeField(null=True)),
                ('publicada_por', models.TextField(null=True)),
                ('retirada_em', models.DateTimeField(null=True)),
                ('retirada_por', models.TextField(null=True)),
            ],
            options={
                'ordering': ['-inicio', 'titulo', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(django.db.models.lookups.GreaterThanOrEqual(django.db.models.functions.text.Length('titulo'), 1), django.db.models.lookups.LessThanOrEqual(django.db.models.functions.text.Length('titulo'), 120)), name='oportunidade_titulo_tamanho'), models.CheckConstraint(condition=models.Q(django.db.models.lookups.GreaterThanOrEqual(django.db.models.functions.text.Length('resumo'), 1), django.db.models.lookups.LessThanOrEqual(django.db.models.functions.text.Length('resumo'), 300)), name='oportunidade_resumo_tamanho'), models.CheckConstraint(condition=models.Q(('categoria__in', ['cursos', 'eventos', 'pesquisa_extensao', 'carreira', 'empreendedorismo', 'outras'])), name='oportunidade_categoria_valida'), models.CheckConstraint(condition=models.Q(('endereco', ''), _negated=True), name='oportunidade_endereco_nao_vazio'), models.CheckConstraint(condition=models.Q(('inicio__lte', models.F('fim'))), name='oportunidade_periodo_coerente'), models.CheckConstraint(condition=models.Q(('publico_unidades__isnull', True), ('publico_unidades__len__gte', 1), _connector='OR'), name='oportunidade_publico_unidades_nao_vazio'), models.CheckConstraint(condition=models.Q(('publico_unidades__contains', ['']), _negated=True), name='oportunidade_publico_unidades_sem_cadeia_vazia'), models.CheckConstraint(condition=models.Q(('publico_niveis__isnull', True), ('publico_niveis__len__gte', 1), _connector='OR'), name='oportunidade_publico_niveis_nao_vazio'), models.CheckConstraint(condition=models.Q(('publico_niveis__contains', ['']), _negated=True), name='oportunidade_publico_niveis_sem_cadeia_vazia'), models.CheckConstraint(condition=models.Q(('publico_cursos__isnull', True), ('publico_cursos__len__gte', 1), _connector='OR'), name='oportunidade_publico_cursos_nao_vazio'), models.CheckConstraint(condition=models.Q(('publico_cursos__contains', ['']), _negated=True), name='oportunidade_publico_cursos_sem_cadeia_vazia'), models.CheckConstraint(condition=models.Q(models.Q(('publicada_em__isnull', True), ('publicada_por__isnull', True)), models.Q(('publicada_em__isnull', False), ('publicada_por__isnull', False)), _connector='OR'), name='oportunidade_publicacao_com_operador'), models.CheckConstraint(condition=models.Q(models.Q(('retirada_em__isnull', True), ('retirada_por__isnull', True)), models.Q(('retirada_em__isnull', False), ('retirada_por__isnull', False)), _connector='OR'), name='oportunidade_retirada_com_operador'), models.CheckConstraint(condition=models.Q(('publicada_em__isnull', True), ('retirada_em__isnull', True), ('retirada_em__gte', models.F('publicada_em')), _connector='OR'), name='oportunidade_retirada_depois_da_publicacao')],
            },
        ),
    ]
