# Generated by Django 5.2.17 on 2026-10-09 22:37

import django.db.models.functions.text
import django.db.models.lookups
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_oportunidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manifestacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pessoa_id', models.UUIDField()),
                ('conclusao_id', models.UUIDField()),
                ('unidade', models.TextField(blank=True)),
                ('forma', models.TextField(choices=[('mentoria', 'Mentoria'), ('experiencia', 'Compartilhar experiência'), ('oportunidade', 'Oferecer oportunidade'), ('pesquisa_extensao', 'Pesquisa e extensão'), ('parceria', 'Parceria'), ('historia', 'Contar sua história')])),
                ('mensagem', models.TextField(blank=True, default='')),
                ('email', models.TextField()),
                ('versao_da_ciencia', models.TextField()),
                ('registrada_em', models.DateTimeField()),
                ('contato_registrado_em', models.DateTimeField(null=True)),
                ('contato_registrado_por', models.TextField(null=True)),
                ('retirada_em', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ['-registrada_em', 'id'],
                'indexes': [models.Index(fields=['pessoa_id'], name='manifestacao_pessoa')],
                'constraints': [models.CheckConstraint(condition=models.Q(('forma__in', ['mentoria', 'experiencia', 'oportunidade', 'pesquisa_extensao', 'parceria', 'historia'])), name='manifestacao_forma_valida'), models.CheckConstraint(condition=models.Q(django.db.models.lookups.LessThanOrEqual(django.db.models.functions.text.Length('mensagem'), 500)), name='manifestacao_mensagem_tamanho'), models.CheckConstraint(condition=models.Q(django.db.models.lookups.GreaterThanOrEqual(django.db.models.functions.text.Length('email'), 3), django.db.models.lookups.LessThanOrEqual(django.db.models.functions.text.Length('email'), 254)), name='manifestacao_email_tamanho'), models.CheckConstraint(condition=models.Q(('versao_da_ciencia', ''), _negated=True), name='manifestacao_versao_nao_vazia'), models.CheckConstraint(condition=models.Q(models.Q(('contato_registrado_em__isnull', True), ('contato_registrado_por__isnull', True)), models.Q(('contato_registrado_em__isnull', False), ('contato_registrado_por__isnull', False)), _connector='OR'), name='manifestacao_contato_com_operador'), models.CheckConstraint(condition=models.Q(('contato_registrado_em__isnull', True), ('contato_registrado_em__gte', models.F('registrada_em')), _connector='OR'), name='manifestacao_contato_depois_do_registro'), models.CheckConstraint(condition=models.Q(('retirada_em__isnull', True), ('retirada_em__gte', models.F('registrada_em')), _connector='OR'), name='manifestacao_retirada_depois_do_registro'), models.UniqueConstraint(condition=models.Q(('retirada_em__isnull', True)), fields=('pessoa_id', 'conclusao_id', 'forma'), name='manifestacao_uma_ativa_por_forma_e_formacao')],
            },
        ),
    ]
