# Generated by Django 5.2.17 on 2026-10-05 01:20

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplementoDaConclusao',
            fields=[
                ('conclusao', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='complemento', serialize=False, to='academico.conclusaoacademica')),
                ('ano_ingresso', models.PositiveSmallIntegerField()),
                ('data_ingresso', models.DateField(null=True)),
                ('obtido_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('data_ingresso__isnull', True), ('ano_ingresso', django.db.models.functions.datetime.ExtractYear('data_ingresso')), _connector='OR'), name='complemento_ano_coerente_com_data')],
            },
        ),
        migrations.CreateModel(
            name='ContextoInstitucionalAgregado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fonte', models.TextField()),
                ('metrica', models.TextField(choices=[('conclusoes_curso_unidade_ano', 'Conclusões do curso na unidade no ano'), ('conclusoes_unidade_ano', 'Conclusões da unidade no ano')])),
                ('curso', models.TextField(null=True)),
                ('unidade', models.TextField()),
                ('ano', models.PositiveSmallIntegerField()),
                ('valor', models.PositiveIntegerField()),
                ('apurado_em', models.DateField()),
                ('obtido_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('fonte', 'metrica', 'curso', 'unidade', 'ano', 'apurado_em'), name='agregado_chave_unica', nulls_distinct=False), models.CheckConstraint(condition=models.Q(models.Q(('curso__isnull', False), ('metrica', 'conclusoes_curso_unidade_ano')), models.Q(('curso__isnull', True), ('metrica', 'conclusoes_unidade_ano')), _connector='OR'), name='agregado_curso_conforme_metrica'), models.CheckConstraint(condition=models.Q(('fonte', ''), _negated=True), name='agregado_fonte_nao_vazio'), models.CheckConstraint(condition=models.Q(('curso', ''), _negated=True), name='agregado_curso_nao_vazio'), models.CheckConstraint(condition=models.Q(('unidade', ''), _negated=True), name='agregado_unidade_nao_vazio')],
            },
        ),
    ]
