# Generated by Django 5.2.17 on 2026-10-02 11:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VinculoDeGovernanca',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identificador_operador', models.TextField()),
                ('papel', models.TextField(choices=[('CPAEG', 'Comissão Própria de Acompanhamento do Egresso (CPAEG)'), ('CSAEG', 'Comissão Setorial de Acompanhamento de Egressos (CSAEG)')])),
                ('unidade', models.TextField(default='')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['identificador_operador', 'papel', 'unidade'],
                'constraints': [models.CheckConstraint(condition=models.Q(('identificador_operador', ''), _negated=True), name='vinculo_identificador_nao_vazio'), models.CheckConstraint(condition=models.Q(('papel__in', ['CPAEG', 'CSAEG'])), name='vinculo_papel_valido'), models.CheckConstraint(condition=models.Q(models.Q(('papel', 'CPAEG'), ('unidade', '')), models.Q(('papel', 'CSAEG'), models.Q(('unidade', ''), _negated=True)), _connector='OR'), name='vinculo_unidade_conforme_papel'), models.UniqueConstraint(fields=('identificador_operador', 'papel', 'unidade'), name='vinculo_unico')],
            },
        ),
    ]
