# Generated by Django 5.2.17 on 2026-10-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeracaoDeVideo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('chave', models.CharField(max_length=64)),
                ('template', models.CharField(max_length=40)),
                ('estado', models.CharField(choices=[('SOLICITADO', 'Solicitado'), ('PROCESSANDO', 'Processando'), ('PRONTO', 'Pronto'), ('FALHOU', 'Falhou')], max_length=12)),
                ('composicao', models.JSONField(null=True)),
                ('video', models.BinaryField(null=True)),
                ('tamanho', models.PositiveIntegerField(null=True)),
                ('motivo', models.CharField(blank=True, max_length=40)),
                ('solicitado_em', models.DateTimeField()),
                ('iniciado_em', models.DateTimeField(null=True)),
                ('concluido_em', models.DateTimeField(null=True)),
                ('expira_em', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['estado', 'solicitado_em'], name='video_fila'), models.Index(fields=['expira_em'], name='video_expiracao')],
                'constraints': [models.UniqueConstraint(fields=('chave',), name='video_chave_unica'), models.CheckConstraint(condition=models.Q(models.Q(('estado', 'PRONTO'), _negated=True), ('video__isnull', False), _connector='OR'), name='video_pronto_tem_video'), models.CheckConstraint(condition=models.Q(models.Q(('estado', 'FALHOU'), _negated=True), models.Q(('motivo', ''), _negated=True), _connector='OR'), name='video_falha_tem_motivo'), models.CheckConstraint(condition=models.Q(models.Q(('estado', 'SOLICITADO'), _negated=True), ('composicao__isnull', False), _connector='OR'), name='video_solicitado_tem_composicao')],
            },
        ),
    ]
