# Generated by Django 5.2.17 on 2026-10-04 21:07

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormacaoDeclarada',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.TextField()),
                ('unidade', models.TextField()),
                ('nivel', models.TextField()),
                ('curso', models.TextField()),
                ('ano_conclusao', models.PositiveSmallIntegerField()),
                ('identificador_cpf', models.CharField(db_index=True, max_length=64)),
                ('verificador', models.CharField(db_index=True, max_length=64)),
                ('chave_de_criacao', models.UUIDField(unique=True)),
                ('declarada_em', models.DateTimeField()),
            ],
            options={
                'ordering': ['declarada_em', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('nome', ''), _negated=True), name='declaracao_nome_nao_vazio'), models.CheckConstraint(condition=models.Q(('unidade', ''), _negated=True), name='declaracao_unidade_nao_vazio'), models.CheckConstraint(condition=models.Q(('nivel', ''), _negated=True), name='declaracao_nivel_nao_vazio'), models.CheckConstraint(condition=models.Q(('curso', ''), _negated=True), name='declaracao_curso_nao_vazio'), models.CheckConstraint(condition=models.Q(('identificador_cpf__regex', '^[0-9a-f]{64}$')), name='declaracao_cpf_hex'), models.CheckConstraint(condition=models.Q(('verificador__regex', '^[0-9a-f]{64}$')), name='declaracao_par_hex')],
            },
        ),
        migrations.CreateModel(
            name='DadosConsultaAcervo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('selado', models.TextField()),
                ('formacao', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='dados_consulta', to='declaracao.formacaodeclarada')),
            ],
        ),
        migrations.CreateModel(
            name='AcessoAosDadosDeConsulta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operador', models.TextField()),
                ('acessado_em', models.DateTimeField()),
                ('formacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='declaracao.formacaodeclarada')),
            ],
        ),
        migrations.CreateModel(
            name='ReferenciaDeAcervo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unidade', models.TextField()),
                ('referencia', models.TextField()),
                ('nivel', models.TextField()),
                ('curso', models.TextField()),
                ('ano_conclusao', models.PositiveSmallIntegerField()),
                ('modalidade', models.TextField(null=True)),
                ('forma_oferta', models.TextField(null=True)),
                ('data_conclusao', models.DateField(null=True)),
                ('registrada_em', models.DateTimeField()),
                ('operador', models.TextField()),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('unidade', 'referencia'), name='acervo_referencia_unica'), models.CheckConstraint(condition=models.Q(('data_conclusao__isnull', True), ('ano_conclusao', django.db.models.functions.datetime.ExtractYear(models.F('data_conclusao'))), _connector='OR'), name='acervo_ano_coerente'), models.CheckConstraint(condition=models.Q(('unidade', ''), _negated=True), name='acervo_unidade_nao_vazio'), models.CheckConstraint(condition=models.Q(('referencia', ''), _negated=True), name='acervo_referencia_nao_vazio'), models.CheckConstraint(condition=models.Q(('nivel', ''), _negated=True), name='acervo_nivel_nao_vazio'), models.CheckConstraint(condition=models.Q(('curso', ''), _negated=True), name='acervo_curso_nao_vazio'), models.CheckConstraint(condition=models.Q(('modalidade', ''), _negated=True), name='acervo_modalidade_nao_vazio'), models.CheckConstraint(condition=models.Q(('forma_oferta', ''), _negated=True), name='acervo_forma_oferta_nao_vazio')],
            },
        ),
        migrations.CreateModel(
            name='ValidacaoDaFormacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resultado', models.CharField(choices=[('CONFIRMADA', 'Formação confirmada'), ('NAO_CONFIRMADA', 'Formação não confirmada')], max_length=14)),
                ('fora_da_abrangencia_na_validacao', models.BooleanField()),
                ('conflito_detectado_na_validacao', models.BooleanField()),
                ('registrada_em', models.DateTimeField()),
                ('operador', models.TextField()),
                ('conclusao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='academico.conclusaoacademica')),
                ('formacao', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='validacao', to='declaracao.formacaodeclarada')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('conclusao__isnull', False), ('resultado', 'CONFIRMADA')), models.Q(('conclusao__isnull', True), ('resultado', 'NAO_CONFIRMADA')), _connector='OR'), name='validacao_conclusao_confirmada'), models.CheckConstraint(condition=models.Q(('resultado', 'CONFIRMADA'), models.Q(('conflito_detectado_na_validacao', False), ('fora_da_abrangencia_na_validacao', False)), _connector='OR'), name='validacao_nao_confirmada_sem_fatos'), models.CheckConstraint(condition=models.Q(('conflito_detectado_na_validacao', False), ('fora_da_abrangencia_na_validacao', False), _connector='OR'), name='validacao_conflito_compativel')],
            },
        ),
    ]
