# Generated by Django 5.2.17 on 2026-10-01 16:42

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instrumento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campanha',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.TextField()),
                ('inicio', models.DateField(null=True)),
                ('fim', models.DateField(null=True)),
                ('ano_minimo', models.PositiveSmallIntegerField(null=True)),
                ('ano_maximo', models.PositiveSmallIntegerField(null=True)),
                ('unidades', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None)),
                ('niveis', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None)),
                ('modalidades', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None)),
                ('formas_oferta', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None)),
                ('aberta_em', models.DateTimeField(null=True)),
                ('encerrada_em', models.DateTimeField(null=True)),
                ('versao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='instrumento.versao')),
            ],
            options={
                'ordering': ['inicio', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('nome', ''), _negated=True), name='campanha_nome_nao_vazio'), models.CheckConstraint(condition=models.Q(models.Q(('fim__isnull', True), ('inicio__isnull', True)), models.Q(('fim__isnull', False), ('inicio__isnull', False), ('inicio__lte', models.F('fim'))), _connector='OR'), name='campanha_periodo_coerente'), models.CheckConstraint(condition=models.Q(('ano_minimo__isnull', True), ('ano_maximo__isnull', True), ('ano_minimo__lte', models.F('ano_maximo')), _connector='OR'), name='campanha_anos_ordenados'), models.CheckConstraint(condition=models.Q(('unidades__isnull', True), ('unidades__len__gte', 1), _connector='OR'), name='campanha_unidades_nao_vazio'), models.CheckConstraint(condition=models.Q(('unidades__contains', ['']), _negated=True), name='campanha_unidades_sem_cadeia_vazia'), models.CheckConstraint(condition=models.Q(('niveis__isnull', True), ('niveis__len__gte', 1), _connector='OR'), name='campanha_niveis_nao_vazio'), models.CheckConstraint(condition=models.Q(('niveis__contains', ['']), _negated=True), name='campanha_niveis_sem_cadeia_vazia'), models.CheckConstraint(condition=models.Q(('modalidades__isnull', True), ('modalidades__len__gte', 1), _connector='OR'), name='campanha_modalidades_nao_vazio'), models.CheckConstraint(condition=models.Q(('modalidades__contains', ['']), _negated=True), name='campanha_modalidades_sem_cadeia_vazia'), models.CheckConstraint(condition=models.Q(('formas_oferta__isnull', True), ('formas_oferta__len__gte', 1), _connector='OR'), name='campanha_formas_oferta_nao_vazio'), models.CheckConstraint(condition=models.Q(('formas_oferta__contains', ['']), _negated=True), name='campanha_formas_oferta_sem_cadeia_vazia'), models.CheckConstraint(condition=models.Q(('aberta_em__isnull', True), models.Q(('fim__isnull', False), ('inicio__isnull', False)), _connector='OR'), name='campanha_aberta_tem_periodo'), models.CheckConstraint(condition=models.Q(('encerrada_em__isnull', True), ('aberta_em__isnull', False), _connector='OR'), name='campanha_encerrada_foi_aberta'), models.CheckConstraint(condition=models.Q(('encerrada_em__isnull', True), models.Q(('aberta_em__isnull', False), ('encerrada_em__gte', models.F('aberta_em'))), _connector='OR'), name='campanha_encerrada_depois_de_aberta')],
            },
        ),
    ]
