# Generated by Django 5.2.17 on 2026-10-04 16:09

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("academico", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialDeVerificacao",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("identificador_cpf", models.TextField(db_index=True)),
                ("verificador", models.TextField(null=True)),
                ("atualizado_em", models.DateTimeField()),
                (
                    "pessoa",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="academico.pessoa",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("identificador_cpf__regex", "^[0-9a-f]{64}$")),
                        name="acesso_identificador_hex",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("verificador__isnull", True),
                            ("verificador__regex", "^[0-9a-f]{64}$"),
                            _connector="OR",
                        ),
                        name="acesso_verificador_hex",
                    ),
                ],
            },
        ),
    ]
